name: Gmail Push Notification

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email via Gmail SMTP
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.GMAIL_USER }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: "🚨 New Git Push to ${{ github.repository }}"
          body: |
            Repo: ${{ github.repository }}
            Pusher: ${{ github.actor }}
            Branch: ${{ github.ref }}
            Commit: ${{ github.sha }}
          to: ${{ secrets.GMAIL_TO }}
          from: ${{ secrets.GMAIL_USER }}
