name: Email on Push

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send email notification
        run: |
          curl -s --user 'api:YOUR_MAILGUN_API_KEY' \
          https://api.mailgun.net/v3/YOUR_DOMAIN_NAME/messages \
          -F from='GitHub Repo <you@yourdomain.com>' \
          -F to=youremail@example.com \
          -F subject="Push to $(git rev-parse --abbrev-ref HEAD)" \
          -F text="A push just occurred on your GitHub repository."
